### ISSUE TITLE
[应用创建]页面RabbitMQ消费者创建参数

### ISSUE THREAD

**Issue by orangedeng** [biblesyme/haier#10]
RabbitMQ消费者创建参数：
* producerApplicationName(dropdown)
* exchangeName(dropdown)
* queueName(input)
* topicName(input if select a topic exchange type)
* RouteKey(input if select a direct exchange type)

**Comment by n313893254** [comment]
![1 -19-2018 15-21-31](https://user-images.githubusercontent.com/18737885/35139108-9dde2820-fd2c-11e7-9a53-112fafa64184.gif)

**Comment by n313893254** [comment]
Fixed
