### ISSUE TITLE
[应用创建]进入主页后设置默认菜单为创建应用

### ISSUE THREAD

**Issue by orangedeng** [biblesyme/haier#14]
进入主页之后，默认显示是`应用创建`页面，但左侧菜单栏为资源审批页面

**Comment by n313893254** [comment]
![1 -19-2018 15-50-02](https://user-images.githubusercontent.com/18737885/35139990-73a2187e-fd30-11e7-9af2-e18b47d66455.gif)

**Comment by n313893254** [comment]
Fixed
