### ISSUE TITLE
[领域管理]新建逻辑完善

### ISSUE THREAD

**Issue by orangedeng** [biblesyme/haier#18]
请完善领域新建逻辑，在新建时，需要填入一个领域管理员信息
在报文结构体中添加以下架构，并传入账号即可

```json
"admin":{
"account":"S01234"
}
```

**Comment by n313893254** [comment]
![image](https://user-images.githubusercontent.com/18737885/35140625-ea955b74-fd32-11e7-9161-92e78101f734.png)
![image](https://user-images.githubusercontent.com/18737885/35140634-f1f5c656-fd32-11e7-9226-a3b4a150ecd2.png)
