### ISSUE TITLE
[领域管理]团队长维护页面无需输入用户名

### ISSUE THREAD

**Issue by orangedeng** [biblesyme/haier#5]
团队长维护页面，按照项目成员维护页面一样的逻辑，输入用户账号即可

**Comment by orangedeng** [comment]
<img width="557" alt="2018-01-19 10 32 41" src="https://user-images.githubusercontent.com/15376837/35132091-82daa2e2-fd04-11e7-8004-382d6194386c.png">

**Comment by orangedeng** [comment]
领完请完善团队长维护操作

**Comment by n313893254** [comment]
![image](https://user-images.githubusercontent.com/18737885/35138479-c02f6342-fd29-11e7-973b-85147fc536de.png)
![image](https://user-images.githubusercontent.com/18737885/35138488-ca825cc8-fd29-11e7-9a3a-bacc2d722837.png)

**Comment by n313893254** [comment]
Fixed
